### PR TITLE
Tweak docs and API for shared numeric types

### PR DESCRIPTION
**Pull request by cmyr**
*This is based off of #216, which should go in first.*

Once we release 1.0, any public API that exists cannot be removed
without requiring us to release a new major version. Motivated by this,
I would to make sure that our public API surface is reasonable concise.

This PR removes a few helper methods and a few trait implementations. If
it turns out that these are needed in the future, they can be added back
without it being a breaking change.

### CODE REVIEW

**Comment by cmyr** [comment]
I'm wondering if we could just get rid of `IntegerOrFloat`, and figure out a way we serialize as an integer when that is possible, at serialization time?

**Comment by cmyr** [comment]
I also wonder if we could move these two types into `font_info.rs`, then they wouldn't need to be part of the top-level docs?

**Comment by madig** [comment]
> I'm wondering if we could just get rid of `IntegerOrFloat`, and figure out a way we serialize as an integer when that is possible, at serialization time?

I'd be happy to not have a custom type for basic types just to get custom serialization behavior. I suppose we'd need a custom `struct Kerning` then which wraps a HashMap of stuff? It could even have a custom `get(first, second)` method for lookup, like defcon and ufoLib2 do :) I'd have done this before, but I bristled at boilerplate-reimplementing HashMap methods.

**Comment by madig** [comment]
That could work I think, actually. It loses the correct-by-construction thing  but we have to call `validate()` anyway...

**Review by madig — APPROVED** [review]

**Comment by cmyr** [comment]
it would be correct by construction, though, since we will fail to deserialize if the number is negative?

**Comment by cmyr** [comment]
oh I see your point. We *could* keep `NonNegativeX` around, if we wanted... 🤔

**Comment by madig** [comment]
Yes, maybe let's replace IntegerOrFloat by a serde attribute for now (FontInfo and Kerning I guess?) and tie the existence of the other to a better idea for how to implement FontInfo?

**Comment by cmyr** [comment]
it's actually more annoying than I thought, because I can't get the attribute to work for the various `Option<Vec<IntegerOrFloat>>` 🤔

**Comment by madig** [comment]
Ah yes. I think you have to write serde functions for the whole type, not just the innermost part.

**Comment by cmyr** [comment]
I couldn't figure out how to serialize/deserialize a sequence while *also* providing a custom serialization function for each member. I didn't dig too deeply, but I suspect I'll have to open an issue.

**Pull request merged**
