### PR TITLE
Use IndexSet instead of Vec for codepoints

### PR DESCRIPTION
**Pull request by cmyr**
This ensures that codepoints are unique, but also respects the original order in which they appear in the file.

This is an alternative to #268. Although it brings in a dependency, it leads to a much simpler and more efficient implementation overall.

Thoughts @madig ?

### CODE REVIEW

**Comment by madig** [comment]
The readme says:

> Preserves insertion order as long as you don't call .remove().

Hm :) Are we gonna let that stop our OCD?

**Comment by madig** [comment]
Otherwise, I'm ok with pulling it in and exposing it directly in the API. I don't like making delegation functions...

**Comment by cmyr** [comment]
So I'm okay going either way with this. Fwiw it would be easy enough to modify the contents without needing to have the crate in scope, e.g.

```rust
my_glyph.codepoints.clear();
my_glyph.codepoints.extend(['a', 'b', 'c']);
```

but I think maybe not having it be public API *is* a strictly better design, so I'll go ahead and do that.

**Comment by cmyr** [comment]
Okay, I've updated this with a new custom Codepoints type, wrapping an indexset.

**Comment by cmyr** [comment]
@RickyDaMa unfortunately I can't use `impl Iterator` with the `IntoIterator` trait. :(

**Pull request merged**
