### PR TITLE
I don't think the fontinfo and glyph mods need to be pub?

### PR DESCRIPTION
**Pull request by madig**
Does `error` need to be pub? :thinking:

### CODE REVIEW

**Comment by cmyr** [comment]
I have a line in runebender, `use norad::glyph::{Contour, ContourPoint, Glyph, GlyphName, PointType};`. I assume all these types are now exported elsewhere?

**Comment by madig** [comment]
It should all be top-level now.

**Comment by madig** [comment]
As in, `use norad::{Contour, ContourPoint, Glyph, GlyphName, PointType};.`.

**Review by cmyr — APPROVED** [review]
sounds good!

**Pull request merged**
