### PR TITLE
[wip] drop file handles off-thread

### PR DESCRIPTION
**Pull request by cmyr**
@madig here is a sketch of having a separate "file handle dropping" thread. Let me know if this shows a measurable speedup on windows? If it does I'll clean it up and figure out a way to make this windows-only.

see #109

### CODE REVIEW

**Comment by madig** [comment]
Cool :D might take me a while to test this on Windows. I wonder if there's a handle limit on Windows we have to obey...

**Comment by madig** [comment]
This seems to do nothing on my Windows machine.

Before, loading and saving https://github.com/madig/noto-amalgamated/tree/main/NotoAmalgamated-Regular.ufo with load_save.rs:

```
loaded 60967 glyphs from an unnamed font in 7.772s.
wrote UFO to disk in 43.483s
loaded 60967 glyphs from an unnamed font in 7.600s.
wrote UFO to disk in 44.758s
loaded 60967 glyphs from an unnamed font in 7.544s.
wrote UFO to disk in 43.289s
```

This branch:

```
loaded 60967 glyphs from an unnamed font in 8.231s.
wrote UFO to disk in 44.176s
loaded 60967 glyphs from an unnamed font in 7.494s.
wrote UFO to disk in 44.153s
loaded 60967 glyphs from an unnamed font in 7.486s.
wrote UFO to disk in 44.119s
```

**Comment by cmyr** [comment]
hm, that's disappointing, maybe this code isn't doing what I think it is? Unfortunately I don't have a PC here to play with...

**Comment by madig** [comment]
I think I have to, at some point, get into profiling with Windows tools to figure out where all the time goes...

**Comment by madig** [comment]
Let's maybe keep this around and open until I find the time to look into it :)

**Pull request closed without merging**
