### PR TITLE
Fix bug where glyphs were saved twice

### PR DESCRIPTION
**Pull request by cmyr**
As pointed out in https://github.com/linebender/norad/pull/157.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
ping @madig in case you were profiling I/O with the main branch

**Comment by madig** [comment]
Thanks, but I haven't gotten around to profiling at all :(

**Comment by madig** [comment]
So, I did a very quick replacement in my test program of `norad = { git = "https://github.com/linebender/norad.git", rev = "bcb1ddf425aa8e6d9da3a945ac2e7e10e6717e47", features = ["rayon"] }` and the runtime is unchanged. I don't know if I'm overlooking something.

**Comment by cmyr** [comment]
yea, I profiled this and it looks like rayon is a small win, which I interpret as meaning that the bottleneck is actually writing to disk, which makes sense.

**Pull request merged**
